[project]
name = "nixpkgs-updaters-library"
description = "A boilerplate-less updater for Nixpkgs ecosystems"
version = "0.1.0"
authors = [
  { name = "Perchun Pak}", email = "pypi@perchun.it" },
]


[tool.setuptools]
packages = [ "nupd" ]


[build-system]
build-backend = 'setuptools.build_meta'
requires = [ 'setuptools' ]
