[project]
name = "nixpkgs-updaters-library"
description = "Library for nixpkgs plugin updaters"
version = "0.1.0"
authors = [
  { name = "Perchun Pak}", email = "pypi@perchun.it" },
]


[build-system]
build-backend = 'setuptools.build_meta'
requires = [ 'setuptools' ]
