from __future__ import annotations

import os
import sys
import typing as t

from packaging.version import parse as parse_version
from pydantic import BaseModel

sys.path.insert(0, os.path.abspath(".."))  # noqa: PTH100

from nupd import __version__

# -- Project information -----------------------------------------------------

project = "nixpkgs-updaters-library"
copyright = "nixpkgs-updaters-library, Perchun Pak"
author = "Perchun Pak"

parsed_version = parse_version(__version__)
# The short X.Y version
version = parsed_version.base_version
# The full version, including alpha/beta/rc tags
release = str(parsed_version)

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosummary",
    "sphinx.ext.autosectionlabel",
    # Used to reference for third party projects:
    "sphinx.ext.intersphinx",
]

autoclass_content = "both"
autodoc_member_order = "bysource"

autodoc_default_options = {
    "members": "",
    "undoc-members": "code,error_template",
    "exclude-members": "__dict__,__weakref__,model_config",
}
autodoc_inherit_docstrings = False

# Automatically generate section labels:
autosectionlabel_prefix_document = True

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

add_module_names = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "navigation_with_keys": True,
}

# -- Extension configuration -------------------------------------------------

# Third-party projects documentation references:
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

napoleon_numpy_docstring = False


# -- Mocks -------------------------------------------------------------------
def mock_autodoc() -> None:
    """Don't add ``Bases: object`` to the classes, that do not have parents.

    See also https://stackoverflow.com/a/75041544/20952782.
    """
    from sphinx.ext import autodoc  # noqa: PLC0415

    class MockedClassDocumenter(autodoc.ClassDocumenter):
        @t.override
        def add_line(self, line: str, source: str, *lineno: int) -> None:
            if line == "   Bases: :py:class:`object`":
                return
            super().add_line(line, source, *lineno)

    autodoc.ClassDocumenter = MockedClassDocumenter


mock_autodoc()

# Don't inherit docstrings from pydantic
del BaseModel.__doc__
del BaseModel.__init__.__doc__
