name: Validation

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        run: nix develop --command ruff check --output-format=github --show-fixes --exit-non-zero-on-fix .

      - name: Run formatter
        run: nix develop --command ruff format --diff .

      - name: Run type checker
        run: nix develop --command basedpyright .
